# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_defender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GoalKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gk_saves', models.IntegerField()),
                ('is_gk', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=32)),
                ('player_number', models.IntegerField()),
                ('player_team', models.CharField(max_length=32)),
                ('player_scoring', models.IntegerField()),
                ('player_assist', models.IntegerField()),
                ('player_minutes', models.IntegerField()),
            ],
        ),
    ]
