# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attacker', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(default='', max_length=32)),
                ('home_team', models.CharField(max_length=32)),
                ('away_team', models.CharField(max_length=32)),
                ('home_goal', models.IntegerField()),
                ('away_goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Midfielder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_midfielder', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='defender',
            name='player_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='goalkeeper',
            name='player_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='midfielder',
            name='player_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='attacker',
            name='player_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='match_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Match'),
        ),
    ]
